In [2]:
import os, sys
import logging

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from joblib import dump
from model import model, fields

ValueError: list.remove(x): x not in list

In [2]:
train_path = '/home/users/datasets/criteo_train1'

In [3]:
numeric_features = ["if"+str(i) for i in range(1,14)]
categorical_features = ["cf"+str(i) for i in range(1,27)]

fields = ["id", "label"] + numeric_features + categorical_features + ["day_number"]

In [4]:
read_table_opts = dict(sep="\t", names=fields, index_col=False)
df = pd.read_table(train_path, **read_table_opts)
df = df.sample(n=int(df.shape[0]/5), random_state=1)
drop_columns = ['cf1', 'cf10', 'cf20', 'cf21', 'cf22'] + ['label', 'id', 'day_number']
y = df['label']
df.drop(columns=drop_columns, inplace=True)

In [9]:
df[categorical_features].head()

,cf1,cf2,cf3,cf4,cf5,cf6,cf7,cf8,cf9,cf10,...,cf17,cf18,cf19,cf20,cf21,cf22,cf23,cf24,cf25,cf26
2565776,ad98e872,43ced263,12648fac,6521d620,c6fc10d3,6fcd6dcb,366faf55,67e82b4c,7cee8453,62da11e3,...,d20856aa,b8170bba,cc7a7d35,156cbe87,96fbe197,15562d5d,d3df7183,c80dc2c0,991321ea,e1be5ef2
3990993,62770d79,b0809051,71ad49a8,6521d620,3a57336e,919c68e4,73804abe,41b753f8,2e4e821f,2e027dc1,...,d20856aa,b8170bba,9512c20b,c38e2f28,14f65a5d,25b1b089,d7c1fc0b,6a920cea,ff654802,ed10571d
2365340,9e06f5c5,a407abec,f413ee45,6faef306,9813d341,6fcd6dcb,0d4e4dfb,9e10c7bd,46dedfa6,2829b4b0,...,NaN,a1eb1511,1889c49d,01b5e745,85a8f883,24d4c408,NaN,73389dcf,991321ea,ed10571d
8859155,99e8eda8,929c447a,2e1930d6,386c49ee,1315f676,6fcd6dcb,b755bb54,8f551379,46dedfa6,a846f696,...,1f7fc70b,628f1b8d,139221a3,09abbe71,a6fe76dc,76f0d13f,bb413871,fbc5d07a,991321ea,2f33557c
5923398,c9a5336e,629ca633,d06269bc,eec6568a,c6fc10d3,6fcd6dcb,8e886148,038e402d,25dd8f9a,53bcdcea,...,NaN,b8170bba,9512c20b,3680d03f,e852ec0b,7c892e37,NaN,49c60617,0b3c06d0,b757e957

In [22]:
co
for col in categorical_features:
    stats = df[col].agg(['nunique', 'count', 'size'])
    
    print(f"{col} nunique={stats[0]}, count={stats[1]}, size={stats[2]}\n")

cf1 nunique=471414, count=1921160, size=2005836

cf2 nunique=18400, count=2005836, size=2005836

cf3 nunique=14483, count=2005836, size=2005836

cf4 nunique=6926, count=2005836, size=2005836

cf5 nunique=18674, count=2005836, size=2005836

cf6 nunique=3, count=2005836, size=2005836

cf7 nunique=6544, count=2005836, size=2005836

cf8 nunique=1265, count=2005836, size=2005836

cf9 nunique=47, count=2005836, size=2005836

cf10 nunique=353011, count=1921160, size=2005836

cf11 nunique=75253, count=1921160, size=2005836

cf12 nunique=63833, count=2005836, size=2005836

cf13 nunique=10, count=2005836, size=2005836

cf14 nunique=2075, count=1309650, size=2005836

cf15 nunique=7371, count=2005836, size=2005836

cf16 nunique=58, count=1309650, size=2005836

cf17 nunique=3, count=1309650, size=2005836

cf18 nunique=924, count=2005836, size=2005836

cf19 nunique=14, count=2005836, size=2005836

cf20 nunique=510475, count=1921160, size=2005836

cf21 nunique=201049, count=1921160, size=2005836

cf22 nunique=430234, count=1921160, size=2005836

cf23 nunique=58603, count=1309650, size=2005836

cf24 nunique=9216, count=2005836, size=2005836

cf25 nunique=71, count=2005836, size=2005836

cf26 nunique=33, count=2005836, size=2005836

In [7]:
["cf"+str(i) for i in range(1,27) if i not in [1,10,20,21,22]]

['cf2',
 'cf3',
 'cf4',
 'cf5',
 'cf6',
 'cf7',
 'cf8',
 'cf9',
 'cf11',
 'cf12',
 'cf13',
 'cf14',
 'cf15',
 'cf16',
 'cf17',
 'cf18',
 'cf19',
 'cf23',
 'cf24',
 'cf25',
 'cf26']

In [ ]:
5

In [ ]:
"""

Обучение
------------------------
cd ozon-masters-bigdata 
projects/1/train.sh 1 /home/users/datasets/criteo_train1


Предсказание
------------------------
cd ozon-masters-bigdata
#remove output dataset if exists
hdfs dfs -rm -r -f -skipTrash predicted.csv
projects/1/predict.sh projects/1/predict.py,projects/1/model.py,1.joblib /datasets/criteo_valid1_features predicted.csv predict.py


projects/1/scorer_local.py /home/users/datasets/criteo_valid_large_filtered_labels  'http://head1:50070/webhdfs/v1/user/ValentinMSU17/pred_with_filter/part-00000?op=OPEN'


projects/1/filter_predict.sh projects/1/filter.py,projects/1/predict.py,projects/1/filter_cond.py,1.joblib,projects/1/model.py /datasets/criteo_valid_large_features pred_with_filter filter.py predict.py
"""